### ISSUE TITLE
Cant see chat messages and all the cameras 

### ISSUE THREAD

**Issue by laxmikantG** [mrgnr/camus#1]
Hi 
I joined on your live chat and was trying to check if could - audio/video call, desktop share? 
Options were available there but was not able to check the functionalities end to end. 
There were issues I found - 
1. Chat messages were not going across
2. Joined all the list of Users were not appearing in Video Feeds
3. I could not find the option to invite a user. 

Is there any way you can explain me?

Also, I want to try this out on local without  docker, how can I use it?
BTW what are you using for STUN/TURN communication?

Thanks 
Laxmikant R

**Comment by mrgnr** [comment]
Hi @laxmikantG, thanks for your feedback :)

A few questions: Which browser are you using? Which browser version? Which operating system?

So far, I've tested Camus with Chromium 83, Firefox 77, Safari 13.1, and Edge 83. Audio/video streaming, desktop sharing, and sending text messages should work reliably with those browsers. I can't guarantee that Camus will work with older versions of those browsers or other browsers since the WebRTC APIs are constantly evolving and some features are not supported by older browsers.

I recommend trying the following:
- Use Chromium, Chrome, Firefox, Safari, or Edge and update to the most recent version.
- Make sure you have JavaScript enabled.
- To use camera and microphone, you must allow access to them when prompted by your browser. Screen sharing and text messaging should still work though, even if you don't have your camera or microphone enabled.
- You can open multiple tabs in your browser for the same chat room. This will allow you to simulate multiple users.

There's currently not a built-in way to invite other users to a room. You just have to copy the URL of the room and send it to someone else.

If you don't want to use Docker, you can install Camus using pip. See the [installation documentation](https://docs.camus.chat/en/latest/installation.html#using-python).

For STUN/TURN, I have a [coturn](https://github.com/coturn/coturn) server running at turn.camus.chat. If you're using the [demo server](https://camus.chat/), the client will first try to establish a direct peer-to-peer connection, then automatically fall back to using TURN if that fails. If you run your own instance of Camus and want to use TURN, you'll have to set up your own TURN server and [set `TURN_HOST`, `TURN_PORT`, and `TURN_STATIC_AUTH_SECRET`](https://github.com/mrgnr/camus/blob/master/camus/config.py).

**Comment by laxmikantG** [comment]
@mrgnr  - Hi Thanks for the response and answer to my queries.

I am building same application, so I was looking for existing code which would reduce my efforts and speed up the development phase. 

I tried your application on 5 different devices:

1. Windows 8 with - `Google Chrome Version 84.0.4147.89 (Official Build) (64-bit)`
2. Windows 10 with - `Google Chrome Version 83+ `  (don't remember exact version, but its updated one)
3. Windows 8 with - `Microsoft Edge Version 83.0.478.64` 
4. Realme 6 pro on Android 10 with  Google Chrome 83.0.4103.106`
5. Redmi note 7 pro with Android 10 with  Google Chrome 83+

It was lagging a bit. and other issues like I mentioned in earlier comment. 


Let me try installing on local. with Google's stun/turn service to test it out. 

Thank you again.
Laxmikant R

**Comment by mrgnr** [comment]
@laxmikantG I did some testing with the devices and browsers you mentioned (except Realme 6 Pro) using [BrowserStack](https://www.browserstack.com/) and didn't find any broken functionality. Lag in video streaming can most likely be attributed to network conditions or hardware.


The server for the [camus.chat](https://camus.chat/) site is intended to provide a demo and is not a production-grade deployment. It's a single server located in Germany, so if your connection happens to use TURN and you're outside of Germany, I'd expect there to be (possibly significant) lag. In v0.2 I plan to add support for specifying a custom TURN server from the client as well as controls for bandwidth & video quality, so problems with lag will be reduced.

Please let me know if you are able to reproduce your issues while doing local testing.
