### ISSUE TITLE
Deploy to Heroku

### ISSUE THREAD

**Issue by ccns1** [mrgnr/camus#2]
Any help or tutorial?

Thanks in advance

**Comment by mrgnr** [comment]
Hi @ccns1, thanks for your question. I'm actively looking into this and should have support for Heroku in the coming days.

**Comment by ccns1** [comment]
Hi @mrgnr , 

Thanks for reply. For me; Only one script is working on Heroku ( https://github.com/Neos21/webrtc-video-chat ) maybe it will be helpful for you.

Also, I have next question; Is it possible in your script set-up only one way streaming to many?

Thanks.

**Comment by mrgnr** [comment]
@ccns1 Heroku support has been added. To deploy, click this button

[![Deploy to
Heroku](https://www.herokucdn.com/deploy/button.svg)](https://heroku.com/deploy?template=https://github.com/mrgnr/camus)

or see the [deployment docs](https://docs.camus.chat/en/latest/deployment.html) for manual deployment instructions.

Regarding your question, there's not really a good way to do one-to-many broadcasting. WebRTC is a peer-to-peer protocol, so every user sends a copy of their stream to every other user. So for example, if there were 100 people in a room and only one of them was streaming, there would be 99 copies of that stream being sent to the other users.

**Comment by ccns1** [comment]
@mrgnr first of all thank you for Heroku deploy template, it is working fine!

Is it possible to implement RTCMultiConnection library ( https://github.com/muaz-khan/RTCMultiConnection ) in your script?

Or edit script that only one streamer will be able to broadcast to many? Thanks.

**Comment by mrgnr** [comment]
@ccns1 Sorry for the delay in replying. Glad to hear that Heroku is working for you!

I took a look at [RTCMultiConnection](https://github.com/muaz-khan/RTCMultiConnection) and it seems to use a sort of mesh networking to forward media streams between clients. I think this is an interesting idea, but there will always be trade-offs between bandwidth usage and latency since WebRTC is inherently a peer-to-peer protocol. An alternative solution would be to implement a selective forwarding unit (SFU) to forward streams from the server to connected clients. For the 0.2 release, I'm focusing on improving and adding features to the user interface. I'll be thinking more about client scalability for the 0.3 release.

Since the original issue (Heroku) has been addressed, I'll go ahead and close this issue. Nevertheless, thanks for your interest in the project and feel free to open another issue if you wish to discuss anything further! :)
